# Base de dados com 30 livros usando dicionários
meus_livros = [
    {"titulo": "1984", "autor": "George Orwell", "ano": 1949, "catalogo": "Distopia"},
    {"titulo": "O Hobbit", "autor": "Tolkien", "ano": 1937, "catalogo": "Fantasia"},
    {"titulo": "O Senhor dos Anéis", "autor": "Tolkien", "ano": 1954, "catalogo": "Fantasia"},
    {"titulo": "Fundação", "autor": "Isaac Asimov", "ano": 1951, "catalogo": "Ficção Científica"},
    {"titulo": "Eu, Robô", "autor": "Isaac Asimov", "ano": 1950, "catalogo": "Ficção Científica"},
    {"titulo": "Duna", "autor": "Frank Herbert", "ano": 1965, "catalogo": "Ficção Científica"},
    {"titulo": "Fahrenheit 451", "autor": "Ray Bradbury", "ano": 1953, "catalogo": "Distopia"},
    {"titulo": "Admirável Mundo Novo", "autor": "Aldous Huxley", "ano": 1932, "catalogo": "Distopia"},
    {"titulo": "O Guia do Mochileiro das Galáxias", "autor": "Douglas Adams", "ano": 1979, "catalogo": "Ficção Científica"},
    {"titulo": "Neuromancer", "autor": "William Gibson", "ano": 1984, "catalogo": "Cyberpunk"},
    {"titulo": "A Revolução dos Bichos", "autor": "George Orwell", "ano": 1945, "catalogo": "Sátira"},
    {"titulo": "Dom Quixote", "autor": "Miguel de Cervantes", "ano": 1605, "catalogo": "Clássico"},
    {"titulo": "Cem Anos de Solidão", "autor": "Gabriel García Márquez", "ano": 1967, "catalogo": "Realismo Mágico"},
    {"titulo": "O Alquimista", "autor": "Paulo Coelho", "ano": 1988, "catalogo": "Aventura"},
    {"titulo": "A Menina que Roubava Livros", "autor": "Markus Zusak", "ano": 2005, "catalogo": "Ficção Histórica"},
    {"titulo": "Harry Potter e a Pedra Filosofal", "autor": "J.K. Rowling", "ano": 1997, "catalogo": "Fantasia"},
    {"titulo": "O Código Da Vinci", "autor": "Dan Brown", "ano": 2003, "catalogo": "Suspense"},
    {"titulo": "A Guerra dos Tronos", "autor": "George R.R. Martin", "ano": 1996, "catalogo": "Fantasia"},
    {"titulo": "Clean Code", "autor": "Robert C. Martin", "ano": 2008, "catalogo": "Tecnologia"},
    {"titulo": "Python Fluente", "autor": "Luciano Ramalho", "ano": 2015, "catalogo": "Tecnologia"},
    {"titulo": "O Programador Pragmático", "autor": "Andrew Hunt", "ano": 1999, "catalogo": "Tecnologia"},
    {"titulo": "Design Patterns", "autor": "Erich Gamma", "ano": 1994, "catalogo": "Tecnologia"},
    {"titulo": "Sapiens", "autor": "Yuval Noah Harari", "ano": 2011, "catalogo": "História"},
    {"titulo": "Homo Deus", "autor": "Yuval Noah Harari", "ano": 2015, "catalogo": "História"},
    {"titulo": "O Pequeno Príncipe", "autor": "Antoine de Saint-Exupéry", "ano": 1943, "catalogo": "Infantil"},
    {"titulo": "Moby Dick", "autor": "Herman Melville", "ano": 1851, "catalogo": "Aventura"},
    {"titulo": "O Grande Gatsby", "autor": "F. Scott Fitzgerald", "ano": 1925, "catalogo": "Romance"},
    {"titulo": "Orgulho e Preconceito", "autor": "Jane Austen", "ano": 1813, "catalogo": "Romance"},
    {"titulo": "Crime e Castigo", "autor": "Fiódor Dostoiévski", "ano": 1866, "catalogo": "Romance"},
    {"titulo": "Os Miseráveis", "autor": "Victor Hugo", "ano": 1862, "catalogo": "Ficção Histórica"}
]